language: c
compiler:
  - gcc
# For linux systems
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev
    - samtools
    - libhts-dev
    - automake
    - r-base
install:
  - sudo apt-get install -qq automake
  - sudo apt-get install -qq r-base
  - sudo Rscript -e "install.packages(c('argparse','yaml','zoo'), repos='http://cran.us.r-project.org')"
  - sudo Rscript -e "install.packages('gada', repos='http://R-Forge.R-project.org')"
  - sudo Rscript -e "install.packages('gada', repos='http://R-Forge.R-project.org')"
  - sudo Rscript -e 'install.packages("mrmosaic", repos=NULL, type="source")'
#  - (set -e -x; wget 'https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2' &&  tar xf samtools-1.3.1.tar.bz2 && cd samtools-1.3.1/ && make && sudo make install )
  - (cd samtools-1.3 && ./configure && make)
  - autoreconf -f -i 
